@startuml name
!define table(x)     class x << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
!define foreign_key(x) <i>x</i>

left to right direction
skinparam classAttributeIconSize 0

table(チャット) {
  primary_key(id)        : INT
  foreign_key(room_id)   : INT
  sender_type            : ENUM
  content                : VARCHAR(512)
  image_path             : VARCHAR(512)
  created_at             : DATETIME
}

table(質問) {
  primary_key(id)        : INT
  title                  : VARCHAR(255)
  content                : TEXT
  asker_type             : ENUM
  image_path             : VARCHAR(512)
  created_at             : DATETIME
}

table(課題) {
  primary_key(id)        : INT
  titles                 : VARCHAR(255)
  description            : TEXT
  creator_type           : ENUM
  due_date               : DATE
  created_at             : DATETIME
  image_path             : VARCHAR(512)
}

table(成果物) {
  primary_key(id)        : INT
  titles                 : VARCHAR(255)
  description            : TEXT
  submitter_type         : ENUM
  image_path             : VARCHAR(512)
  file_path              : VARCHAR(512)
  created_at             : DATETIME
}

table(カレンダー) {
  primary_key(id)        : INT
  titles                 : VARCHAR(255)
  description            : TEXT
  scheカレンダー  : ENUM
  related_type           : ENUM
  foreign_key(related_id): INT
  schedule_date          : DATE
  created_at             : DATETIME
}

table(マイルストーン) {
  primary_key(id)        : INT
  titles                 : VARCHAR(255)
  description            : TEXT
  date                   : DATE
  created_at             : DATETIME
}

table(タスク) {
  primary_key(id)        : INT
  titles                 : VARCHAR(255)
  description            : TEXT
  assigned_to_name       : VARCHAR(255)
  status                 : ENUM
  due_date               : DATE
  created_at             : DATETIME
}

table(お知らせ) {
  primary_key(id)        : INT
  titles                 : VARCHAR(255)
  content                : TEXT
  image_path             : VARCHAR(512)
  poster_type            : ENUM
  created_at             : DATETIME
}

table(要望) {
  primary_key(id)        : INT
  requester_type         : ENUM
  target_type            : ENUM
  target_id              : INT
  content                : TEXT
  created_at             : DATETIME
}


カレンダー <== タスク
カレンダー <== マイルストーン
カレンダー <== お知らせ


@enduml
